# Generated by Django 2.2 on 2019-12-15 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0002_auto_20191214_1902'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
