# Generated by Django 2.2 on 2019-12-26 19:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beautyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addduration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Addprice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Addstaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('mobileno', models.CharField(max_length=12)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beautyapp.Citys')),
            ],
        ),
        migrations.CreateModel(
            name='Paymentmod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2019, 12, 27, 0, 51, 3, 982817))),
                ('gname', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=100)),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('price', models.CharField(max_length=50)),
                ('comments', models.CharField(default='NA', max_length=500)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beautyapp.Citys')),
                ('duration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Addduration')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Paymentmod')),
                ('services', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beautyapp.Services')),
                ('treatment_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Addstaff')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2019, 12, 27, 0, 51, 3, 982817))),
                ('particular', models.CharField(max_length=250)),
                ('bill_no', models.CharField(max_length=400)),
                ('amount', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=250)),
                ('reciept', models.ImageField(upload_to='Images/expenses/')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beautyapp.Citys')),
            ],
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('remarks', models.CharField(default='present', max_length=250)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Addstaff')),
            ],
        ),
    ]
