# Generated by Django 2.2 on 2019-12-15 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20191214_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 12, 15, 22, 24, 19, 539838)),
        ),
    ]
