# Generated by Django 2.2.7 on 2020-01-01 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20191227_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 1, 3, 50, 41, 866612)),
        ),
        migrations.AlterField(
            model_name='guest',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 1, 3, 50, 41, 865040)),
        ),
    ]
