# Generated by Django 2.2 on 2019-12-17 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20191217_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 12, 17, 19, 49, 17, 851953)),
        ),
    ]
