# Generated by Django 2.2.7 on 2019-12-17 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20191217_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 12, 17, 15, 27, 22, 600413)),
        ),
    ]
