# Generated by Django 2.2.7 on 2020-01-02 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200102_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='out',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 2, 12, 52, 8, 298541)),
        ),
        migrations.AlterField(
            model_name='guest',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 2, 12, 52, 8, 296393)),
        ),
    ]
